# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # Every Vagrant virtual environment requires a box to build off of.
  #config.vm.box = "bento/ubuntu-16.04"
  config.vm.box = "bento/centos-7.4"
#config.vm.box = "mrvantage/centos7-minikube"
  config.vm.boot_timeout = 1000

  # Fixes changes from https://github.com/mitchellh/vagrant/pull/4707
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--memory", 65536] # RAM allocated to each VM
    #vb.customize ["modifyvm", :id, "--cpus", 12]

    vb.customize ["modifyvm", :id, "--memory", 16384]
    vb.customize ["modifyvm", :id, "--cpus", 4]
  end

  config.disksize.size='100GB'

  #config.vm.provision :shell, :path => "bootstrap.sh"

  #config.vm.provision :shell, :path => "bootstrap_centos.sh"

  config.vm.define :h1 do |h1|
    h1.vm.hostname="h1.local.com"
    h1.vm.network :private_network, ip: "192.168.3.101"
#
  end


end